# @package _group_
_target_: on_policy.algos.a2c.A2C
model:
  actor:
    - 64
    - 64
  critic:
    - 64
    - 64
  activation: 'relu' # options: 'relu' or 'tanh'
  device: cpu

# number of updates of behavioural policy at which the exploitation algorithm is updated
update_freq: 1
importance_sampling: default # 'default' or 'retrace'

greedy_evaluation: true

lr: 3e-4
max_grad_norm: 0.5
use_gae: False
gae_lambda: 0.95
entropy_coef: 0.0
kl_coef: 0.0
value_loss_coef: 0.5
adam_eps: 0.001
gamma: 0.99
use_proper_time_limits: True
n_steps: 5