# @package _group_
_target_: intrinsic_rewards.ride.ride.RIDE

model:
  architecture: fc # "fc" or "conv"
  count:
    type: dict # "hash" or "dict"
    key_dim: 16
    decay_factor: 1.0
    bucket_sizes:
        - 999931
        - 999953
        - 999959
        - 999961
        - 999979
        - 999983
  state_representation:
    - 64
    - 64
    - 16
  forward_model:
    - 64
  inverse_model:
    - 64
  device: cpu

lr: 1e-5
max_grad_norm: 40.
intrinsic_reward_coef: 0.5
forward_loss_coef: 10.0
inverse_loss_coef: 0.1
