# @package _group_
version: 1
formatters:
  simple:
    format: '(%(process)d) [%(levelname)s] - (%(asctime)s) - %(name)s >> %(message)s'
    datefmt: '%m/%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.job.name}.log
root:
  level: INFO
  handlers: [console]

disable_existing_loggers: false